### ISSUE TITLE
Two gits for the same extension ?

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/cronstatus#14]
Hi,

i found:
- https://github.com/ForumHulp/cronstatus
- https://github.com/BoardTools/cronstatus

What is the difference and why ? What is the git that is more updated

**Comment by ForumHulp** [comment]
There is no difference.
I started it and Igor wanted to have a github of its own

**Comment by Galixte** [comment]
Ok the good is here: https://github.com/BoardTools/cronstatus
